// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package stream

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	RequestTimestamp     int64    `protobuf:"varint,1,opt,name=requestTimestamp,proto3" json:"requestTimestamp,omitempty"`
	ResponseTimestamp    int64    `protobuf:"varint,2,opt,name=responseTimestamp,proto3" json:"responseTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetRequestTimestamp() int64 {
	if m != nil {
		return m.RequestTimestamp
	}
	return 0
}

func (m *Header) GetResponseTimestamp() int64 {
	if m != nil {
		return m.ResponseTimestamp
	}
	return 0
}

type Body struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Request struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *Body    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *Body    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "stream.Header")
	proto.RegisterType((*Body)(nil), "stream.Body")
	proto.RegisterType((*Request)(nil), "stream.Request")
	proto.RegisterType((*Response)(nil), "stream.Response")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x8d, 0x2e, 0xab, 0x4e, 0x45, 0xeb, 0x5c, 0x94, 0x9e, 0x4a, 0x0e, 0x52, 0x44, 0x8a,
	0xae, 0x2f, 0x20, 0x5e, 0xf4, 0x9c, 0xed, 0x0b, 0x64, 0x93, 0x41, 0x17, 0xdc, 0x26, 0x4e, 0x62,
	0xa1, 0x0f, 0xe7, 0xbb, 0x49, 0x67, 0xb7, 0xf4, 0xd0, 0x93, 0xe2, 0x2d, 0xcc, 0xff, 0xe7, 0x9b,
	0x2f, 0x04, 0xe0, 0x8d, 0xa3, 0x9b, 0x47, 0x0e, 0x39, 0x60, 0x99, 0x32, 0x93, 0xed, 0x74, 0x03,
	0xe5, 0x2b, 0x59, 0x4f, 0x8c, 0xb7, 0x30, 0x66, 0xfa, 0xfc, 0xa2, 0x94, 0x17, 0x6d, 0x47, 0x29,
	0xdb, 0x2e, 0x5e, 0xab, 0xa9, 0x9a, 0x1d, 0x99, 0xbd, 0x39, 0xde, 0xc1, 0x25, 0x53, 0x8a, 0x61,
	0x99, 0x68, 0x57, 0x3e, 0x94, 0xf2, 0x7e, 0xa0, 0x27, 0x50, 0x3c, 0x07, 0xbf, 0x46, 0x84, 0xc2,
	0xdb, 0x6c, 0x85, 0x7a, 0x6a, 0xe4, 0xac, 0x6b, 0x38, 0x36, 0x3d, 0x1d, 0x6f, 0xa0, 0x7c, 0x17,
	0x15, 0x29, 0x8c, 0xaa, 0xf3, 0x79, 0xef, 0x38, 0xef, 0x05, 0xcd, 0x90, 0xe2, 0x14, 0x8a, 0x26,
	0xf8, 0xb5, 0xec, 0x1b, 0x55, 0x67, 0xdb, 0xd6, 0x66, 0x85, 0x91, 0x44, 0x2f, 0xe0, 0xc4, 0x0c,
	0x16, 0xff, 0x47, 0xad, 0xbe, 0x15, 0x14, 0x2f, 0x1c, 0x1d, 0x3e, 0x00, 0x70, 0x74, 0x35, 0xf1,
	0xaa, 0x75, 0x84, 0x17, 0xdb, 0xea, 0xf0, 0x8e, 0xc9, 0x78, 0x37, 0xe8, 0x1d, 0xf4, 0x01, 0x3e,
	0xc1, 0x55, 0x22, 0x5e, 0x11, 0xd7, 0xad, 0xa7, 0x5a, 0xe2, 0xdf, 0xdc, 0xbf, 0x57, 0x1b, 0x82,
	0xfb, 0x68, 0x69, 0x99, 0xff, 0x46, 0x98, 0xa9, 0xa6, 0x94, 0x9f, 0x7f, 0xfc, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0x5e, 0xe1, 0xa5, 0x07, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcClient interface {
	RpcService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ServerSideStreamService(ctx context.Context, in *Request, opts ...grpc.CallOption) (Grpc_ServerSideStreamServiceClient, error)
	ClientSideStreamService(ctx context.Context, opts ...grpc.CallOption) (Grpc_ClientSideStreamServiceClient, error)
}

type grpcClient struct {
	cc *grpc.ClientConn
}

func NewGrpcClient(cc *grpc.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) RpcService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/stream.Grpc/rpcService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) ServerSideStreamService(ctx context.Context, in *Request, opts ...grpc.CallOption) (Grpc_ServerSideStreamServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Grpc_serviceDesc.Streams[0], "/stream.Grpc/serverSideStreamService", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcServerSideStreamServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Grpc_ServerSideStreamServiceClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type grpcServerSideStreamServiceClient struct {
	grpc.ClientStream
}

func (x *grpcServerSideStreamServiceClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcClient) ClientSideStreamService(ctx context.Context, opts ...grpc.CallOption) (Grpc_ClientSideStreamServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Grpc_serviceDesc.Streams[1], "/stream.Grpc/clientSideStreamService", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcClientSideStreamServiceClient{stream}
	return x, nil
}

type Grpc_ClientSideStreamServiceClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type grpcClientSideStreamServiceClient struct {
	grpc.ClientStream
}

func (x *grpcClientSideStreamServiceClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcClientSideStreamServiceClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcServer is the server API for Grpc service.
type GrpcServer interface {
	RpcService(context.Context, *Request) (*Response, error)
	ServerSideStreamService(*Request, Grpc_ServerSideStreamServiceServer) error
	ClientSideStreamService(Grpc_ClientSideStreamServiceServer) error
}

func RegisterGrpcServer(s *grpc.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_RpcService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).RpcService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.Grpc/RpcService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).RpcService(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_ServerSideStreamService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcServer).ServerSideStreamService(m, &grpcServerSideStreamServiceServer{stream})
}

type Grpc_ServerSideStreamServiceServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type grpcServerSideStreamServiceServer struct {
	grpc.ServerStream
}

func (x *grpcServerSideStreamServiceServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Grpc_ClientSideStreamService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).ClientSideStreamService(&grpcClientSideStreamServiceServer{stream})
}

type Grpc_ClientSideStreamServiceServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type grpcClientSideStreamServiceServer struct {
	grpc.ServerStream
}

func (x *grpcClientSideStreamServiceServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcClientSideStreamServiceServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Grpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stream.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "rpcService",
			Handler:    _Grpc_RpcService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "serverSideStreamService",
			Handler:       _Grpc_ServerSideStreamService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "clientSideStreamService",
			Handler:       _Grpc_ClientSideStreamService_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
